# Generated by Django 2.2.1 on 2019-06-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190606_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ('-num_likes',)},
        ),
    ]
